mesh_files:
  base:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/collision/base.stl"

  shoulder:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/collision/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/collision/upperarm.stl"

  forearm:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/collision/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/collision/wrist1.stl"
    visual_offset: -0.093

  wrist_2:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/ur5/collision/wrist2.stl"
    visual_offset: -0.095

  wrist_3:
    visual:
      mesh: "package://ur5_ros2_gazebo/meshes/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5_ros2_gazebo/meshes/collision/wrist3.stl"
    visual_offset: -0.0818
