trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - panda_arm_controller
  - panda_handleft_controller
  - panda_handright_controller

panda_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

panda_handleft_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - panda_finger_joint1

panda_handright_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - panda_finger_joint2